<%@ Page Language="C#" AutoEventWireup="true" 
    MasterPageFile="~/Master.Master"
    CodeBehind="CheckOut.aspx.cs" Inherits="FinalProject.CheckOut" %>
<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link href="css/checkOut.css" rel="stylesheet" />
        <div class="sp-content">
            <div class="container">
                <div class="sp1">
                    <div class="container-sp2">
                        <div class="img-sp1">
                            &nbsp;<span style="font-weight: lighter; font-size: 13px"><asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" Height="134px" OnRowDeleting="GridView1_RowDeleting" ShowHeaderWhenEmpty="True" Width="674px">
                                <Columns>
                                    <asp:BoundField DataField="productID" HeaderText="ID">
                                    <HeaderStyle Width="50px" />
                                    </asp:BoundField>
                                    <asp:HyperLinkField DataNavigateUrlFields="productID" DataNavigateUrlFormatString="Details.aspx?productID={0}" DataTextField="productName" HeaderText="Product" />
                                    <asp:BoundField DataField="quantity" HeaderText="Quantity" />
                                    <asp:BoundField DataField="total" HeaderText="Total" />
                                </Columns>
                                <HeaderStyle BackColor="#CCCCCC" Font-Bold="True" ForeColor="Black" HorizontalAlign="Center" VerticalAlign="Middle" />
                            </asp:GridView>
</span>
                        </div>
                    </div>
                </div>
                <div class="sp1">
                    <div class="container-sp2">
                        <div class="img-sp1">

                        </div>
                        <div class="infor-sp1">
                            <div class="infor-sp1-I">
                                <table>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td style="text-decoration: line-through; padding-left: 5px;">&nbsp;</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="infor-sp1-r">
                                <br>
                            </div>
                            <br>
                            <br>
                            <br>


                            <p><span style="font-weight: lighter; font-size: 13px"></p>


                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
                <div class="sp1">
                    <div class="container-sp2">
                        <div class="main-img">

                        </div>
                    </div>
                </div>
                <div class="sp1">
                    <div class="container-sp2">
                        <div class="main-img">
                            <div class=" cart-total">
                                &nbsp;<div class="price-details">
                                    <h3>Price Details</h3>
                                    &nbsp; <span style="font-weight: lighter; font-size: 13px">
                                        <h4>TOTAL</h4>
</span>
                                </div>
                                <ul class="total_price">
                                    <li class="last_price" style="height: 36px">
                                    <div class="clearfix" style="height: 37px"><span style="font-weight: lighter; font-size: 13px">
                                        <asp:Label ID="totalLabel" runat="server" Font-Size="Large" Text="Label"></asp:Label>
</span></div>
                                </ul>


                                &nbsp;<div class="total-item">
                                    <span style="font-weight: lighter; font-size: 13px">
                                    <asp:Button ID="Button1" runat="server" Height="41px" Text="Check out" Width="288px" OnClick="Button1_Click" />
</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</span>
</asp:Content>
    